### ISSUE TITLE
Update to latest version of Datatilstander SSB

### ISSUE THREAD

**Issue by mariuslars** [statisticsnorway/dapla-manual-legacy#119]
Update [datatilstander reference](https://github.com/statisticsnorway/dapla-manual/blob/main/dapla-manual/references.bib) to latest version (2nd edition).

Latest version can be found here
https://ssbno.sharepoint.com/sites/Internedokumenter/Delte%20dokumenter/Forms/AllItems.aspx?id=%2Fsites%2FInternedokumenter%2FDelte%20dokumenter%2FInterne%20dokumenter%202023%2F2023%2D14%20Datatilstander%20i%20SSB%2Epdf&parent=%2Fsites%2FInternedokumenter%2FDelte%20dokumenter%2FInterne%20dokumenter%202023

**Comment by skars82** [comment]
Done
https://manual.dapla.ssb.no/datatilstander.html
