### ISSUE TITLE
Add definitions of all 'datatilstander'

### ISSUE THREAD

**Issue by akcssb** [statisticsnorway/dapla-manual-legacy#126]
The page https://manual.dapla.ssb.no/datatilstander.html sends readers to a document outside the dapla manual. The page should instead (or in addition) define and describe these.

**Comment by akcssb** [comment]
Note: The page 'hva er dapla team?' links to a sharepoint document as of now. When this issue is solved the mentioned page should link to the page 'datatilstander'

**Comment by skars82** [comment]
Done 
https://manual.dapla.ssb.no/datatilstander.html
