### ISSUE TITLE
Describe the terminal in more details

### ISSUE THREAD

**Issue by Jonathan7SSB** [statisticsnorway/dapla-manual-legacy#64]
Jeg savner fortsatt en litt nærmere forklaring av terminalen/linux/operativsystemet til JupyterLab Dapla. Jeg forstår at det er Linux operativsystem, men hvor foreligger denne? den er vel en del av Dapla på en eller annen måte?
Blant seksjonene hører jeg noen kaller det "Linux i adminsonen" og noen sier "Dapla-Linux". Kanskje greit å få dette svart på hvitt så det ikke blir noen misforståelser her. adminsone kan jo tolkes som om det er på bakken, slik som linux i prodsone er, så hvor foreligger denne linux delen til JupyterLab Dapla seg?

**Comment by skars82** [comment]
Da har vi lagt til en kort beskrivelse. https://manual.dapla.ssb.no/hva-er-botter.html#lokalt-filsystem-p%C3%A5-dapla
