### ISSUE TITLE
Change section on R in "Nytt ssb-prosject"

### ISSUE THREAD

**Issue by sjentoft** [statisticsnorway/dapla-manual-legacy#67]
Her står det at renv ikke håndtereing versjonering av selv R men det gjøre det: https://manual.dapla.ssb.no/nytt-ssbproject.html#hva-med-r. Versjonen ar r er i lock-filen. Men foreløpig hjelper det ikke nå vi kun har en versjon av R tilgjengelig, men det er en annen sak. Manual bør endres men kanksje vi kan se på hvordan å integrere R i ssb-prosject første?

**Comment by skars82** [comment]
@sjentoft. renv følger med på hvilken R-versjon du bruker, men den hjelper deg ikke å installere den når man ønsker å gjenskape et miljø. Det gjør det vanskeligere å reprodusere tidligere resultater. Lag gjerne en PR som sier dette på en annen måte.
