### ISSUE TITLE
Opprette mappe i lagringsområde fungerer ikke

### ISSUE THREAD

**Issue by rakelgading** [statisticsnorway/dapla-manual-legacy#84]
Måten å opprette mapper på Google Cloud Storage som står i daplamanualen fungerer ikke (https://manual.dapla.ssb.no/jobbe-med-data.html)

Jeg fulgte denne veiledningen:

from dapla import FileClient
fs = FileClient.get_gcs_file_system()

# Example of how you can use gcsfs and dapla-toolbelt together
fs.mkdir("gs://ssb-prod-arbmark-skjema-data-produkt/ledstill/klargjorte-data/sesongjustering/p2023k2")

**Comment by Jonathan7SSB** [comment]
@rakelgading Jeg er litt usikker, og har ikke testet dette, men skjønner det kan være noe forvirrende og. Iht. dokumentasjonen så vil fs.mkdir opprette en ny bøtte: https://gcsfs.readthedocs.io/en/latest/api.html#gcsfs.core.GCSFileSystem.mkdir
Ser av dokumentasjonen der at hvis man vil opprette undermapper i bøttene så bør en benytte fs.mkdirs eller fs.makedirs. Gjerne test ytterligere, men kan hende det da er skrivefeil i manualen her.

**Comment by skars82** [comment]
Du har helt rett, @rakelgading. Eksempelet i manualen fungerer ikke. Det skulle det heller ikke siden `fs.mkdir` det oppretter en bøtte og ikke mappe, slik som @Jonathan7SSB skrev over. Jeg prøvde `fs.makedirs()` som skal opprette mapper, men det funket heller ikke. Siden mapper egentlig ikke finnes i bøtter, så trenger man strengt tatt ikke denne funksjonaliteten. Men hvis du ønsker det så funker det å bruke `fs.touch()`, den testet jeg og det funker. Jeg kan oppdatere dokumentasjon.

**Comment by skars82** [comment]
@rakelgading @Jonathan7SSB Dokmuentasjon er oppdatert
https://manual.dapla.ssb.no/jobbe-med-data.html#opprette-mapper
