### ISSUE TITLE
Feil/Mangel funnet, det mangler ett steg ved opprettelse av PAT

### ISSUE THREAD

**Issue by Jonathan7SSB** [statisticsnorway/dapla-manual-legacy#85]

**Comment by Jonathan7SSB** [comment]
Punktene er som følger:
- I menyen til venstre velger du Personal Access Token, og deretter Tokens (classic).
- Under Note kan du gi PAT’en et navn. Velg et navn som er intuitivt for deg. Hvis du skal bruke PAT til å jobbe mot Dapla, så ville jeg ganske enkelt kalt den dapla. Hvis du skal bruke den mot bakkemiljøet ville jeg kalt den prodsone eller noe annet som gjør det lett for det skjønne innholdet i ettertid.

Mellom disse punktene så må vi jo trykke "Generate new token" og så trykke "Generate new token (classic)" før vi finner Note. 
Det kan nesten se ut som dette er ett punkt som er fjernet på et senere tidspunkt når man ser på qmd filen.
Noen grunn for at dette er blitt utelatt @statisticsnorway/team-statistikktjenester ?

Dette ble reagert på i en Git workshop seksjonen min hadde 02.06.23.

**Comment by skars82** [comment]
Helt enig at det bør være med, @Jonathan7SSB. Kunne du skrevet det inn og laget en PR med meg som reviewer?

**Comment by skars82** [comment]
Manualen er oppdatert
